baseURL = "https://blog.rbby.dev/"
title = "rbby.dev"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  env = "production"
  title = "rbby.dev"
  description = "A clean, minimal blog"
  author = "rbby"

  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/rbbydotdev"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/rbbydotdev"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "newsletter"
  name = "newsletter"
  url = "#newsletter-dialog"
  weight = 30

[[menu.main]]
  identifier = "hire-me"
  name = "hire me"
  url = "https://rbby.dev/resume"
  weight = 40

[[menu.main]]
  identifier = "rbby.dev"
  name = "rbby.dev"
  url = "https://rbby.dev"
  weight = 50


[markup.highlight]
  noClasses = false
  lineNos = false
  style = "monokai"
